import asyncio
import random
import requests
from typing import Dict, Any, Optional
from datetime import datetime
from app.models.agreement import AgreementType, EStampRequest
from app.core.config import settings
from app.services.leegality_client import leegality_client

class EStampService:
    def __init__(self):
        self.stamp_duty_rates = {
            "maharashtra": {
                AgreementType.RENTAL: 0.25,
                AgreementType.EMPLOYMENT: 100,
                AgreementType.SERVICE: 0.1,
                AgreementType.SALE: 5.0,
                AgreementType.PARTNERSHIP: 500
            },
            "karnataka": {
                AgreementType.RENTAL: 0.2,
                AgreementType.EMPLOYMENT: 100,
                AgreementType.SERVICE: 0.1,
                AgreementType.SALE: 4.0,
                AgreementType.PARTNERSHIP: 500
            },
            "delhi": {
                AgreementType.RENTAL: 0.2,
                AgreementType.EMPLOYMENT: 100,
                AgreementType.SERVICE: 0.1,
                AgreementType.SALE: 6.0,
                AgreementType.PARTNERSHIP: 500
            }
        }
    
    def calculate_stamp_duty(self, state: str, agreement_type: AgreementType, property_value: Optional[float] = None) -> float:
        state_lower = state.lower()
        if state_lower not in self.stamp_duty_rates:
            state_lower = "maharashtra"
        
        rate = self.stamp_duty_rates[state_lower].get(agreement_type, 100)
        
        if agreement_type in [AgreementType.RENTAL, AgreementType.SERVICE, AgreementType.SALE] and property_value:
            return (property_value * rate) / 100
        else:
            return rate
    
    async def request_estamp(self, estamp_request: EStampRequest) -> Dict[str, Any]:
        if not settings.LEEGALITY_ENABLED or not settings.LEEGALITY_AUTH_TOKEN:
            return await self._mock_request_estamp(estamp_request)
        
        try:
            stamp_series = f"STAMP_SERIES_{random.randint(100000, 999999)}"
            
            return {
                "status": "success",
                "estamp_id": stamp_series,
                "certificate_url": f"/estamp/certificate/{estamp_request.agreement_id}",
                "amount_paid": estamp_request.stamp_duty_amount,
                "timestamp": datetime.utcnow().isoformat(),
                "state": estamp_request.state,
                "validity": "Valid for 6 months",
                "stamp_series": stamp_series
            }
        except Exception as e:
            return {
                "status": "failed",
                "error": f"eStamp service error: {str(e)}",
                "timestamp": datetime.utcnow().isoformat()
            }
    
    async def _mock_request_estamp(self, estamp_request: EStampRequest) -> Dict[str, Any]:
        await asyncio.sleep(2)
        
        success = random.choice([True, True, True, False])
        
        if success:
            return {
                "status": "success",
                "estamp_id": f"ESTAMP_{random.randint(100000, 999999)}",
                "certificate_url": f"/estamp/certificate/{estamp_request.agreement_id}",
                "amount_paid": estamp_request.stamp_duty_amount,
                "timestamp": datetime.utcnow().isoformat(),
                "state": estamp_request.state,
                "validity": "Valid for 6 months"
            }
        else:
            return {
                "status": "failed",
                "error": "eStamp service temporarily unavailable",
                "timestamp": datetime.utcnow().isoformat()
            }
    
    def generate_mock_estamp_certificate(self, agreement_id: str) -> bytes:
        certificate_content = f"""
        eSTAMP CERTIFICATE
        
        Certificate ID: ESTAMP_{random.randint(100000, 999999)}
        Agreement ID: {agreement_id}
        Issue Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}
        
        This is a mock eStamp certificate for testing purposes.
        In production, this would be generated by the state eStamp authority.
        
        Status: VALID
        """
        return certificate_content.encode('utf-8')

estamp_service = EStampService()
